version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./QuickBite.API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      ConnectionStrings__DefaultConnection: "server=localhost;port=3306;database=quickbite;user=root;password=1234"

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: quickbite
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: