@url = https://localhost:7170/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyYTc3NzIwMy1lZGVmLTQ2OTYtODY0OS0zNzRjZjgzZTIyMWYiLCJnaXZlbl9uYW1lIjoiTW9zdGFmYSIsImZhbWlseV9uYW1lIjoiSmFtYWwiLCJqdGkiOiI2ZjFlNDFhYy00MWVmLTQ2N2MtODdhZC0zZjc2MjdhNDNjMjQiLCJleHAiOjE3NzgwODk1OTksImlzcyI6IlF1aWNrQml0ZSIsImF1ZCI6IlF1aWNrQml0ZSJ9.DmUWfqyov40d7Io4LBxSz_jFhegzX6pQQJ11QiZHQyk

GET {{url}}/dinners
Authorization: Bearer {{token}}