@url = https://localhost:7170/api


POST {{ url }}/auth/register
Content-Type: application/json

{
    "firstName" : "Mostafa",
    "lastName" : "Jamal",
    "email" : "sm.mostafa@gmail.com",
    "password" : "12345678"
}